### ISSUE TITLE
Question about some models

### ISSUE THREAD

**Issue by GaelicThunder** [Gryphe/MergeMonster#4]
Hi, i wanted to know if (or how) is possible to use models that are in the .gguf format and are missing the config.json
I was trying  [this](https://huggingface.co/NeverSleep/Noromaid-7b-v0.2-GGUF) model but it misses the config. I tried to use the base model config.json it is based of (mistral 7b)  but it's not working...
Im kinda newbie when it comes to this stuff, so i wanted to understand it a little better

**Comment by Gryphe** [comment]
Hi! GGUF support unfortunately isn't possible due to the nature of the merging (+ testing) process - It needs the full float16/32 version to be able to function properly. 

Yes, that means it needs a lot of resources, but there's no avoiding that.
